site_name: BTCRecover
site_url: https://btcrecover.readthedocs.io
site_description: Documentation for BTCRecover
site_author: Stephen Rothery
repo_url: https://github.com/3rdIteration/btcrecover
edit_uri: ""
copyright: 3rdIteration/btcrecover is licensed under the GNU General Public License v2.0 - 2021 Stephen Rothery

theme:
    name: material
    features:
        - navigation.tabs
        - navigation.sections
        - toc.integrate
    palette:
        primary: blue
    icon:
        repo: fontawesome/brands/github
    custom_dir: docs/mkdocs_overrides

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
    - Home: index.md
    - Installation & Testing:
        - Installing BTCRecover: INSTALL.md
        - GPU Acceleration: GPU_Acceleration.md
        - Resource Usage and Security Notes: Limitations_and_Caveats.md
        - Viewing this documentation offline: local_mkdocs.md
    - Seed Recovery:
        - Seed Recovery Quickstart: Seedrecover_Quick_Start_Guide.md
        - Seed Word Lists & Languages: wordlist_notes.md
        - Notes on Accounts (Derivation paths) and Altcoins: bip39-accounts-and-altcoins.md
        - BIP39 Seed/Token Lists: BIP39_descrambling_seedlists.md
        - Recovery without Addresses (Address Database): Creating_and_Using_AddressDB.md
        - Basic Seed Recovery Examples: Usage_Examples/basic_seed_recoveries.md
    - Password/Passphrase Recovery:
        - Password Recovery Quickstart: TUTORIAL.md
        - Tokenlist Files: tokenlist_file.md
        - Passwordlist Files: passwordlist_file.md
        - Trustless (or Cloud) Recovery - Creating Wallet Extracts: Extract_Scripts.md
        - Extracting Private Keys from Wallet Files (Decrypt & Dump): Decrypting_dumping_walletfiles.md
        - Basic Password/Passphrase Recovery Examples: Usage_Examples/basic_password_recoveries.md
    - Usage Examples:
        - Examples Overview: Usage_Examples/UsageExamples.md
        - Basic Seed Recovery Examples: Usage_Examples/basic_seed_recoveries.md
        - Basic Password/Passphrase Recovery Examples: Usage_Examples/basic_password_recoveries.md
        - Descrambling a 12 word seed: Usage_Examples/2020-05-02_Descrambling_a_12_word_seed/Example_Descrambling_a_12_word_seed.md
        - Recovering Blockchain.com wallet: Usage_Examples/2020-05-08_Recovering_Blockchain_Wallet_Passwords/Example_Recovering_Blockchain_Wallet_Passwords.md
        - Multi-Worker Descrambling: Usage_Examples/2020-05-23_multi_device_descrambling_12_word_seed_with_extras/Example_multi_device_descrambling_12_word_seed_with_extras.md
        - Multi-GPU Cloud Based Recovery: Usage_Examples/2020-10-06_Multi-GPU_with_vastai/Example_Multi-GPU_with_vastai.md
        - Grouping words together in tokenlist based seed recoveries: Usage_Examples/2022-04-02_Seed_Tokenlist_TokenBlocks/example_seed_tokenlist_tokenblocks.md
    - About:
        - Credits: CREDITS.md
        - License: licence.md
    - Donate: donate.md

plugins:
    - search
    - autolinks
    - include-markdown
    - git-committers:
        repository: 3rdIteration/btcrecover
        branch: master
        token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCEviBQwLv-yfv3BErm0ojHg/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/ytcryptoguide
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ytcryptoguide
    - icon: fontawesome/solid/globe
      link: https://cryptoguide.tips
    - icon: fontawesome/solid/envelope
      link: mailto:steve@cryptoguide.tips
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/user/Crypto-Guide
    - icon: fontawesome/brands/skype
      link: https://join.skype.com/invite/g3fn0EzshP69
