# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Last Push - All Tests (Full Modules)

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-22.04] # Test Ubuntu Only
        python-version: [3.7, 3.8, 3.9, 3.10.5] # Test all suppoorted versions of Python

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-full.txt
        sudo apt install python3-bsddb3
    - name: Run All Tests
      run: |
        python run-all-tests.py -vv
