# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Weekly - All Tests (+Optional Modules)

on:
  schedule:
    - cron: "0 0 * * 6"
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
        python-version: [3.10.5] # Only worry about testing the current Python version

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Build Environment
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install autoconf automake libffi libtool pkg-config python
        fi
      shell: bash
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-full.txt
    - name: Run All Tests
      run: |
        python run-all-tests.py -vv
